INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (1, 1, 25, 'Admiral', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (2, 1, 86, 'Admiral', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (3, 1, 139, 'Admiral', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (4, 3, 4, 'Ahtanum ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (5, 3, 22, 'Ahtanum ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (6, 4, 22, 'Amarillo ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (7, 4, 24, 'Amarillo ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (8, 4, 115, 'Amarillo ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (9, 5, 22, 'Amarillo Gold', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (10, 5, 24, 'Amarillo Gold', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (11, 6, 17, 'Apollo ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (12, 6, 32, 'Apollo ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (13, 6, 88, 'Apollo ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (14, 8, 18, 'Atlas ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (15, 8, 29, 'Aquila ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (16, 9, 18, 'Atlas (Styrian Atlas)', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (17, 10, 131, 'Aurora ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (18, 11, 130, 'Aurora (Super Styrian Aurora)', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL,
        NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (19, 12, 29, 'Banner ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (20, 15, 87, 'Bobek ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (21, 16, 36, 'Bramling Cross', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (22, 16, 105, 'Bramling Cross', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (23, 16, 153, 'Bramling Cross', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (24, 17, 31, 'Bravo ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (25, 17, 143, 'Bravo ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (26, 17, 155, 'Bravo ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (27, 18, 20, 'Brewer''s Gold', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (28, 18, 22, 'Brewer''s Gold', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (29, 18, 27, 'Brewer''s Gold', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (30, 18, 48, 'Brewer''s Gold', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (31, 18, 86, 'Brewer''s Gold', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (32, 18, 87, 'Brewer''s Gold', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (33, 19, 18, 'Bullion ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (34, 19, 27, 'Bullion ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (35, 19, 39, 'Bullion ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (36, 20, 18, 'Bullion ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (37, 20, 27, 'Bullion ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (38, 20, 31, 'Bullion ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (39, 20, 39, 'Bullion ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (40, 20, 48, 'Bullion ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (41, 20, 87, 'Bullion ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (42, 21, 0, 'Calypso ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (43, 22, 24, 'Cascade ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (44, 23, 110, 'Celeia ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (45, 23, 131, 'Celeia ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (46, 24, 20, 'Centennial ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (47, 24, 39, 'Centennial ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (48, 24, 48, 'Centennial ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (49, 24, 88, 'Centennial ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (50, 25, 0, 'Challenger ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (51, 26, 48, 'Chelan ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (52, 27, 20, 'Chinook ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (53, 27, 39, 'Chinook ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (54, 27, 48, 'Chinook ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (55, 27, 88, 'Chinook ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (56, 29, 39, 'Cluster ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (57, 29, 48, 'Cluster ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (58, 30, 46, 'Columbia ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (59, 30, 154, 'Columbia ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (60, 31, 24, 'Columbus ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES
  (61, 32, 27, 'Columbus / Tomahawk / Zeus ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES
  (62, 32, 32, 'Columbus / Tomahawk / Zeus ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES
  (63, 32, 48, 'Columbus / Tomahawk / Zeus ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES
  (64, 32, 87, 'Columbus / Tomahawk / Zeus ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES
  (65, 32, 88, 'Columbus / Tomahawk / Zeus ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES
  (66, 32, 139, 'Columbus / Tomahawk / Zeus ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (67, 33, 0, 'Comet ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (68, 34, 58, 'Crystal ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (69, 34, 72, 'Crystal ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (70, 35, 44, 'Delta ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (71, 35, 154, 'Delta ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (72, 36, 43, 'East Kent Goldings ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (73, 36, 46, 'East Kent Goldings ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (74, 36, 105, 'East Kent Goldings ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (75, 36, 130, 'East Kent Goldings ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (76, 36, 139, 'East Kent Goldings ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (77, 36, 153, 'East Kent Goldings ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (78, 37, 0, 'El Dorado', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (79, 38, 47, 'Ella ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (80, 39, 27, 'Eroica ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (81, 39, 48, 'Eroica ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (82, 39, 87, 'Eroica ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (83, 40, 0, 'Falconer''s Flight', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (84, 41, 0, 'Falconer''s Flight 7C''s Blend ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL,
        NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (85, 43, 34, 'First Gold ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (86, 43, 36, 'First Gold ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (87, 44, 130, 'Fuggle ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (88, 44, 154, 'Fuggle ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (89, 45, 44, 'Fuggle, Organic', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (90, 46, 36, 'Fuggles ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (91, 46, 154, 'Fuggles ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (92, 47, 0, 'Galaxy ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (93, 48, 27, 'Galena ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (94, 48, 29, 'Galena ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (95, 48, 39, 'Galena ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (96, 48, 87, 'Galena ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (97, 49, 61, 'German Tradition ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (98, 49, 69, 'German Tradition ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (99, 49, 72, 'German Tradition ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (100, 51, 36, 'Goldings, B.C.', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (101, 51, 46, 'Goldings, B.C.', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (102, 52, 46, 'Goldings, East Kent ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (103, 52, 51, 'Goldings, East Kent ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (104, 53, 131, 'Green Bullet ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (105, 54, 0, 'Greenburg ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (106, 55, 49, 'Hallertau ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (107, 55, 58, 'Hallertau ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (108, 55, 72, 'Hallertau ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (109, 56, 31, 'Hallertau Magnum ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (110, 56, 57, 'Hallertau Magnum ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (111, 56, 88, 'Hallertau Magnum ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (112, 57, 49, 'Hallertau Taurus', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (113, 57, 56, 'Hallertau Taurus', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (114, 58, 34, 'Hallertauer ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (115, 58, 61, 'Hallertauer ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (116, 58, 72, 'Hallertauer ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (117, 59, 61, 'Hallertauer ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES
  (118, 60, 58, 'Hallertauer Hersbrucker ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES
  (119, 60, 61, 'Hallertauer Hersbrucker ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES
  (120, 60, 72, 'Hallertauer Hersbrucker ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES
  (121, 60, 82, 'Hallertauer Hersbrucker ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES
  (122, 61, 34, 'Hallertauer Mittelfrueh ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES
  (123, 61, 58, 'Hallertauer Mittelfrueh ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES
  (124, 61, 72, 'Hallertauer Mittelfrueh ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES
  (125, 61, 82, 'Hallertauer Mittelfrueh ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (126, 62, 110, 'Harmonie ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (127, 69, 61, 'Hersbrucker ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (128, 69, 72, 'Hersbrucker ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (129, 69, 82, 'Hersbrucker ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (130, 69, 126, 'Hersbrucker ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (131, 71, 75, 'Horizon ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (132, 72, 34, 'Liberty ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (133, 72, 55, 'Liberty ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (134, 72, 82, 'Liberty ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (135, 73, 110, 'Lublin ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (136, 73, 141, 'Lublin ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (137, 74, 110, 'Lublin (Lubelski)', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (138, 74, 124, 'Lublin (Lubelski)', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (139, 74, 141, 'Lublin (Lubelski)', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (140, 75, 32, 'Magnum', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (141, 75, 56, 'Magnum', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (142, 75, 88, 'Magnum', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (143, 77, 27, 'Marynka ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (144, 77, 36, 'Marynka ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES
  (145, 78, 56, 'Merkur (Hallertauer Merkur)', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES
  (146, 78, 75, 'Merkur (Hallertauer Merkur)', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (147, 79, 31, 'Millenium ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (148, 79, 88, 'Millenium ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (149, 79, 143, 'Millenium ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (150, 79, 155, 'Millenium ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (151, 81, 110, 'Motueka ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (152, 82, 34, 'Mt. Hood', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (153, 82, 58, 'Mt. Hood', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (154, 82, 72, 'Mt. Hood', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (155, 83, 44, 'Mt. Rainier', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (156, 83, 55, 'Mt. Rainier', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (157, 84, 0, 'Nelson Sauvin', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (158, 85, 48, 'Newport ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (159, 86, 87, 'Northdown ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (160, 87, 58, 'Northern Brewer ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (161, 87, 61, 'Northern Brewer ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (162, 88, 27, 'Nugget ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (163, 89, 18, 'Olympic ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (164, 91, 97, 'Orion ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (165, 92, 20, 'Pacific Gem ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES
  (166, 93, 27, 'Pacific Hallertau (aka Pacifica)', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL,
   NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES
  (167, 93, 61, 'Pacific Hallertau (aka Pacifica)', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL,
   NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES
  (168, 93, 72, 'Pacific Hallertau (aka Pacifica)', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL,
   NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES
  (169, 93, 82, 'Pacific Hallertau (aka Pacifica)', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL,
   NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (170, 94, 0, 'Pacific Jade', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (171, 95, 27, 'Pacifica ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (172, 95, 61, 'Pacifica ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (173, 96, 154, 'Palisade ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (174, 98, 25, 'Phoenix ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (175, 98, 36, 'Phoenix ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (176, 98, 86, 'Phoenix ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (177, 101, 36, 'Pioneer ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (178, 103, 110, 'Premiant ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (179, 104, 29, 'Pride of Ringwood', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (180, 104, 48, 'Pride of Ringwood', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (181, 105, 46, 'Progress ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (182, 106, 4, 'Rakau (Alpharoma)', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (183, 106, 133, 'Rakau (Alpharoma)', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (184, 108, 109, 'Rubin ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (185, 109, 73, 'Saaz', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (186, 109, 141, 'Saaz', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (187, 110, 73, 'Saaz ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (188, 110, 109, 'Saaz ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (189, 110, 124, 'Saaz ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (190, 111, 121, 'Santiam ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (191, 111, 123, 'Santiam ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (192, 111, 140, 'Santiam ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (193, 112, 61, 'Saphir', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (194, 113, 48, 'Satus ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (195, 114, 110, 'Select Spalt ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (196, 114, 122, 'Select Spalt ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (197, 114, 140, 'Select Spalt ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (198, 116, 110, 'Sladek ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (199, 121, 110, 'Spalt Spalter ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (200, 121, 141, 'Spalt Spalter ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (201, 122, 110, 'Spalter ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (202, 122, 140, 'Spalter ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (203, 123, 110, 'Spalter Select ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (204, 123, 121, 'Spalter Select ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (205, 123, 141, 'Spalter Select ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (206, 124, 73, 'Sterling ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (207, 124, 110, 'Sterling ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (208, 125, 87, 'Sticklebract ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (209, 126, 34, 'Strisslespalt ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (210, 126, 60, 'Strisslespalt ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (211, 126, 82, 'Strisslespalt ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (212, 127, 128, 'Styrian Aurora ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (213, 127, 130, 'Styrian Aurora ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (214, 128, 44, 'Styrian Bobek', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (215, 128, 130, 'Styrian Bobek', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (216, 128, 154, 'Styrian Bobek', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (217, 130, 36, 'Styrian Golding', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (218, 130, 44, 'Styrian Golding', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (219, 130, 154, 'Styrian Golding', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (220, 131, 46, 'Styrian Goldings', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (221, 131, 154, 'Styrian Goldings', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (222, 132, 0, 'Summer ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (223, 133, 31, 'Summit ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (224, 133, 79, 'Summit ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (225, 133, 143, 'Summit ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (226, 133, 152, 'Summit ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (227, 133, 155, 'Summit ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (228, 136, 48, 'Super Galena', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (229, 137, 104, 'Super Pride', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (230, 138, 61, 'Sylva ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (231, 138, 66, 'Sylva ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (232, 139, 36, 'Target ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (233, 140, 110, 'Tettnang ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (234, 140, 121, 'Tettnang ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES
  (235, 141, 61, 'Tettnang (Tettnang Tettnager)', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL,
   NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES
  (236, 141, 110, 'Tettnang (Tettnang Tettnager)', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL,
   NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES
  (237, 141, 121, 'Tettnang (Tettnang Tettnager)', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL,
   NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (238, 142, 26, 'Tillicum ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (239, 142, 48, 'Tillicum ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (240, 143, 27, 'Tomahawk ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (241, 143, 48, 'Tomahawk ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (242, 143, 88, 'Tomahawk ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (243, 143, 143, 'Tomahawk ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (244, 143, 155, 'Tomahawk ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (245, 145, 61, 'Tradition ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (246, 145, 72, 'Tradition ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (247, 145, 147, 'Tradition ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (248, 147, 58, 'Ultra', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (249, 147, 72, 'Ultra', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (250, 147, 110, 'Ultra', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (251, 147, 145, 'Ultra', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (252, 148, 61, 'Vanguard ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES
  (253, 151, 55, 'Wakatu (Hallertau Aroma)', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES
  (254, 151, 72, 'Wakatu (Hallertau Aroma)', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (255, 152, 31, 'Warrior ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (256, 152, 75, 'Warrior ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (257, 152, 88, 'Warrior ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES
  (258, 153, 36, 'Whitbread Golding Variety (WGV)', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL,
   NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES
  (259, 153, 105, 'Whitbread Golding Variety (WGV)', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL,
   NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (260, 154, 36, 'Willamette ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (261, 154, 46, 'Willamette ', NULL, '2014-04-13 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (262, 157, 154, 'Golding', NULL, '2014-10-01 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (263, 157, 158, 'Golding', NULL, '2014-10-01 00:00:00', NULL, NULL, NULL, NULL);
INSERT INTO `HOPS_SUBSTITUTES` (`ID`, `HOP_ID`, `SUBSTITUTES_ID`, `NAME`, `INSERT_ID`, `INSERT_DATE`, `UPDATE_ID`, `UPDATE_DATE`, `DELETE_ID`, `DELETE_DATE`)
VALUES (264, 158, 154, 'Fuggle', NULL, '2014-10-01 00:00:00', NULL, NULL, NULL, NULL);

COMMIT;
